# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Minsuk Kang
tagline:          'blog'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://minskmedve.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://www.instagram.com/ms27.kang/

paginate:         5
